[package]
name = "minmath"
version = "2.1.0"
edition = "2024"
description = "A lightweight math library"
license = "MIT"
repository = "https://github.com/Jodus-Melodus/minmath"
categories = ["mathematics", "data-structures", "game-development", "science"]

[dependencies]
